site_name: Collective Knowledge (CK), Collective Mind (CM) and Common Metadata eXchange (CMX) Documentation

repo_url: https://github.com/mlcommons/ck

theme:
  name: material
  logo: img/logo_v2.svg
  favicon: img/logo_v2.svg
  palette:
    primary: deep purple
    accent: green
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
nav:
  - HOME: index.md
  - CMX/CM:
    - Summary: cmx/README.md
    - Installation: cmx/install.md
    - Understanding CMX: cmx/understanding-cmx.md
    - CMX commands to share and reuse artifacts with common metadata: cmx/common-automation-actions.md
    - CMX automation actions for related artifacts: cmx/specific-automation-actions.md
    - Reusing CMX automations and artifacts for MLOps, DevOps and MLPerf: cmx/cmx4mlops.md
    - Creating new artifacts and automations: cmx/create.md
    - Improving CMX framework: cmx/improving-cmx.md
    - Motivation: cmx/motivation.md
  - MLPerf automations:
    - Summary: cmx/mlperf-inference/README.md
    - MLPerf inference benchmark v4.1: cmx/mlperf-inference/v4.1/README.md
    - MLPerf inference benchmark v5.0: cmx/mlperf-inference/v5.0/README.md
  - CK Playground: https://access.cKnowledge.org
  - Releases: https://github.com/mlcommons/ck/releases

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - macros
