site_name: Collective Knowledge and Common Metadata eXchange Documentation
repo_url: https://github.com/mlcommons/ck
theme:
  name: material
  logo: img/logo_v2.svg
  favicon: img/logo_v2.svg
  palette:
    primary: deep purple
    accent: green
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
nav:
  - HOME: index.md
  - CMX: 
    - Summary: cmx/README.md
    - Introduction: cmx/introduction.md
    - Installation: cmx/install.md
    - Getting Started Guide: cmx/getting-started.md
  - CK Playground: https://access.cKnowledge.org
  - Releases: https://github.com/mlcommons/ck/releases

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - macros
