site_name: Collective Knowledge (CK), Collective Mind (CM) and Common Metadata eXchange (CMX) Documentation

repo_url: https://github.com/mlcommons/ck

theme:
  name: material
  logo: img/logo_v2.svg
  favicon: img/logo_v2.svg
  palette:
    primary: deep purple
    accent: green
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
nav:
  - HOME: index.md
  - CMX/CM: 
    - Summary: cmx/README.md
    - Installation: cmx/install.md
    - Getting Started Guide: cmx/getting-started.md
    - MLOps, DevOps and MLPerf automations: https://access.cknowledge.org/playground/?action=scripts
    - High-level architecture: https://cKnowledge.org/images/cmx-architecture-4.0.0.png
    - Python API: https://cknowledge.org/docs/cmx
    - Motivation: cmx/motivation.md
  - CK Playground: https://access.cKnowledge.org
  - Releases: https://github.com/mlcommons/ck/releases

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - macros
